name: Deploy Hugo Site

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Debug System Information
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Workflow Run Number: ${{ github.run_number }}"
          echo "Current Directory Contents:"
          pwd
          ls -la
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Verify Hugo Installation
        run: |
          hugo version
          which hugo
      
      - name: Build Hugo Site
        run: |
          # 添加详细输出和错误捕获
          hugo --minify \
               --baseURL "https://zjk159357.github.io/Gallery/" \
               -v || (echo "Hugo build failed" && exit 1)
      
      - name: Detailed Build Output Check
        run: |
          echo "Public Directory Contents:"
          ls -la public
          echo "Total files in public:"
          find public | wc -l
          
          # 检查是否有 index.html
          if [ ! -f public/index.html ]; then
            echo "Error: No index.html found in public directory"
            exit 1
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
          retention-days: 1
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Comprehensive Artifact Check
        run: |
          echo "Listing all workflow runs..."
          gh run list --workflow=${{ github.workflow }} --limit 5
          
          echo "Checking artifacts for this run..."
          artifacts=$(gh run view ${{ github.run_id }} --json artifacts)
          echo "$artifacts"
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Deployment Diagnostics
        if: failure()
        run: |
          echo "Deployment failed. Possible reasons:"
          echo "1. No artifacts found"
          echo "2. GitHub Pages configuration issue"
          echo "3. Insufficient permissions"
          echo "4. Artifact upload failed in previous job"
